Rendu Intermédiaire Python pour la datascience - Gabriel Stremsdoerfer

In [64]:
# importation données
import pandas as pd
df = pd.read_csv(
    'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)
df

/tmp/ipykernel_17919/2336434942.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0
...,...,...,...,...,...,...,...
528670,fr_etranger,Français établis hors de France,229,Zurich,NaN,nuls,31
528671,fr_etranger,Français établis hors de France,231,Taipei,NaN,nuls,2
528672,fr_etranger,Français établis hors de France,233,Nour-Soultan,NaN,nuls,0
528673,fr_etranger,Français établis hors de France,234,Monterrey,NaN,nuls,2
528674,fr_etranger,Français établis hors de France,235,Bahamas (Nassau),NaN,nuls,0

1.Exploration générale

In [73]:
# Question 1
from code_exo.exo1.Q1 import question_1

question_1(df)
df

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01001001,Ain,001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01002002,Ain,002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01004004,Ain,004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01005005,Ain,005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01006006,Ain,006,Ambléon,Nathalie,ARTHAUD,0
...,...,...,...,...,...,...,...
528670,fr_etranger229229,Français établis hors de France,229,Zurich,NaN,nuls,31
528671,fr_etranger231231,Français établis hors de France,231,Taipei,NaN,nuls,2
528672,fr_etranger233233,Français établis hors de France,233,Nour-Soultan,NaN,nuls,0
528673,fr_etranger234234,Français établis hors de France,234,Monterrey,NaN,nuls,2
528674,fr_etranger235235,Français établis hors de France,235,Bahamas (Nassau),NaN,nuls,0

In [54]:
# Question 2

In [55]:
# Question 3

2. Comparaison des scores départements aux moyennes nationales

In [56]:
# Question 4

In [57]:
# Question 5

In [58]:
# Question 6

In [59]:
# Question 7

3.Un peu de cartographie

In [60]:
# Question 8